/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import cableado.IConsultas;
import cableado.LoginMenu;
import logica.ManejoConsultas;
import utilidades.Cargador;

/**
 *
 * @author David
 */
public class VistaHistorialConsejero extends javax.swing.JFrame {

    /**
     * Creates new form VistaHistorialConsejero
     */
	
	IConsultas consejero;
	IConsultas estudiante;
    int ancho, alto;
    public VistaHistorialConsejero(IConsultas cons) {
    	consejero = cons;
        initComponents();
        preferencias();
    }
    public void preferencias(){
        setResizable(false);
        setLocationRelativeTo(null);
        ancho = 460;
        alto = 170;
        this.setMinimumSize(new Dimension(ancho,alto)); 
        setTitle("Vista Informacion Estudiante");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        //((JPanel)getContentPane()).setOpaque(false);
        //ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/papel.jpg"));
        //JLabel fondo= new JLabel();
        //fondo.setIcon(uno);
        //getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        //fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel1.setText("Codigo del estudiante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        txtCodigo.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 51, 303, 29));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        btnVolver.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 91, 176, -1));

        btnConsultar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 51, 176, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {
    	if(txtCodigo.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "No ha digitado ningun codigo");
        }else{
        	Cargador car = new Cargador("componentes",ClassLoader.getSystemClassLoader());
    		Class clas = null;
    		try {
    			clas = car.cargarUnaClase(IConsultas.class.getName());
    			if(clas != null) {
    				IConsultas IConsultas = (IConsultas)clas.newInstance();
    				estudiante = IConsultas;
    				estudiante.setCodigoEstudiante(Integer.parseInt(txtCodigo.getText()));
    				if(estudiante.existenciaHistoria()==false){
    					dispose();
    					ManejoConsultas manejo = new ManejoConsultas();
    					manejo.setEstudiante(estudiante);
    					manejo.setConsejero(consejero);
    					manejo.mostrarHistorialConsejero();
    				}else{
    					JOptionPane.showMessageDialog(null, "No se encuentra información sobre el estudiante digitado");
    				}
    			}else{
        			JOptionPane.showMessageDialog(null, "No se encuentra componente ManejoInfoDB");
    			}
    		} catch (Exception e) {
    			e.printStackTrace();
    		}
        }
    }

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    	Cargador cargador = new Cargador("componentes",ClassLoader.getSystemClassLoader());
		Class cls = null;
		try {                 
			cls = cargador.cargarUnaClase(LoginMenu.class.getName());
			if(cls != null) {
                dispose(); 
                LoginMenu LoginMenu = (LoginMenu)cls.newInstance();
                LoginMenu.setConsejero(consejero);
                LoginMenu.mostrarMenuConsejero();
			}else{
    			JOptionPane.showMessageDialog(null, "No se encuentra componente ManejoMenu");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnVolverActionPerformed
    
    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
